config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/cp', as: 'rails_admin'
  resources :flats, only: [:show, :index]

  resources :payments, only: [:create]

  resources :orders, only: [:create, :index]

  # oauth

  get "/auth/:provider/callback" => "sessions#create"
  delete "/signout" => "sessions#destroy", as: :signout

  root to: 'home#show'
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/concerns/presentable.rb
module Presentable
  extend ActiveSupport::Concern

  def shown_name
    presentation_name || name
  end
end

app/models/concerns/sortable.rb
module Sortable
  extend ActiveSupport::Concern

  module ClassMethods
    def sortable(sorting_column, direction = 'desk')
      result = self.where(nil)
      return result unless self.column_names.include?(sorting_column)
      result.reorder "#{sorting_column} #{direction == 'desc' ? 'DESC' : 'ASC'}"
    end
  end
end

app/models/district.rb
class District < ActiveRecord::Base
  include Presentable
  has_many :flats
end

app/models/flat.rb
class Flat < ActiveRecord::Base

  mount_uploader :og_preview, OgPreviewUploader

  include Filterable
  include Sortable

  default_scope -> {order "actual_at DESC"}

  # Filters
  scope :price_from,  -> (price_from) { where "price >= ?", price_from }
  scope :price_to,    -> (price_to)   { where "price <= ?", price_to }
  scope :district,    -> (district)   { where district_id: district }
  scope :address,     -> (address)    { where "address LIKE ?", "%#{address}%" }
  scope :type,        -> (type)       { where type_id: type }

  scope :actual, -> { where "actual_at >= ?", 1.week.ago.utc }

  before_create :update_datestamp
  before_save :generate_og_preview

  belongs_to :district
  belongs_to :type

  def update_datestamp
    actual_at = Date.today
  end

  def similars count = 4
    Flat.actual.where('price < 20000').order('RAND()').limit count
  end

  protected

  def generate_og_preview
    img = MiniMagick::Image.open(Dir[Rails.root.join('app', 'assets', 'images', 'patterns', '*')].sample)
    wrapped_address = Helper.word_wrap(address, line_width: 25)
    wrapped_district = Helper.word_wrap(district.name, line_width: 25)
    caption = "#{wrapped_address}\n#{wrapped_district}\n#{price} руб/мес"
    img.combine_options do |c|
      c.font Rails.root.join('app', 'assets', 'fonts', 'open-sans.ttf')
      c.gravity 'Center'
      c.pointsize '21'
      c.draw "text 0, -10 '#{caption}'"
      c.fill 'white'
      c.gravity 'South'
      c.pointsize '12'
      c.draw "text 0,10 'Ищите больше на sherlock-homes.ru'"
    end
    self.og_preview = img
  end

  module Helper
    extend ActionView::Helpers::TextHelper
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  def accept
    amount_days = APP_CONFIG[:plans][self.amount.to_i]
    self.user.extend_subscription! amount_days
    self.is_done = true
    self.save
  end
end

app/models/type.rb
class Type < ActiveRecord::Base
  include Presentable
  has_many :flats
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :orders

  before_create :set_subscription_expire

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
    end
  end

  def subscribed?
    self.subscription_expire_at > DateTime.now
  end

  def subscription_days_left
    ((self.subscription_expire_at - DateTime.now) / 1.day).to_i + 1
  end

  def extend_subscription! amount
    if self.subscribed?
      self.subscription_expire_at += amount.days
    else
      self.subscription_expire_at = DateTime.now + amount.days
    end  
    self.save
  end

  protected

  def set_subscription_expire
    self.subscription_expire_at = DateTime.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?

  def after_sign_in_path_for(resource)
    if current_user.subscribed?
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    else
      page_path('prices')
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.includes(:type, :district)
      .actual
      .filter(params.slice(:address, :district, :type, :price_from, :price_to))
      .sortable(params[:sort], params[:dir])
      .page(params[:page])
      .decorate
    @districts = District.all
    @types = Type.all
    @price_from_steps = APP_CONFIG[:price_from_steps]
    @price_to_steps = APP_CONFIG[:price_to_steps]

    respond_to :html, :js
  end
  def show
    @flat = Flat.find(params[:id]).decorate

    respond_to :html, :js
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @flats = Flat.includes(:type, :district).actual.page(params[:page]).decorate
    @districts = District.all
    @types = Type.all
    @price_from_steps = APP_CONFIG[:price_from_steps]
    @price_to_steps = APP_CONFIG[:price_to_steps]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.create user: current_user, amount: params[:amount], is_done: false
    @liqpay_request = Liqpay::Request.new(
      amount: @order.amount,
      order_id: @order.id,
      description: 'Оплата подписки на сайте Sherlock Homes',
      result_url: orders_url
    )
  end
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  protect_from_forgery except: :liqpay_payment
  skip_before_filter :verify_authenticity_token
  def create
    @liqpay_response = Liqpay::Response.new(params)
    logger.info "Order ID: #{@liqpay_response.order_id.to_i}"
    logger.info "Amount: #{@liqpay_response.amount.to_i}"
    if @liqpay_response.success?
      order = Order.where(
        id: @liqpay_response.order_id.to_i, 
        amount: @liqpay_response.amount.to_i,
        is_done: false
      ).first
      order.try(:accept)
      logger.info "Order: #{order.id}"
    end
  render plain: 'OK'
  rescue Liqpay::InvalidResponse
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_url path
    path.nil? ? nil : request.protocol + request.host_with_port + path
  end
end

app/views/flats/_details.html.slim
.details(id="flat-#{flat.id}-details")
  .inner
    .map-outer
      .map= flat.static_map
    .description-outer
      .description
        = flat.description.html_safe
        .readmore
          = link_to "#", flat

app/views/flats/_finder.html.slim
/ p Укажите район, количество комнат и ценовой диапазон, чтобы получить самые подходящие для вас варианты.
section#finder
  a#finder-cleaner(href="#") очистить фильтр &#x2715;
  = form_tag flats_path, method: :get, remote: true do 
    .filters
      .viewport-split
        .address
          = text_field_tag :address, params[:address], placeholder: 'Улица и номер дома'
      .viewport-split
        .district
          = select_tag :district, 
            options_from_collection_for_select(@districts, :id, :shown_name, params[:district]), 
            prompt: 'Район'
        .type
          = select_tag :type, 
            options_from_collection_for_select(@types, :id, :shown_name, params[:type]), 
            prompt: 'Комнат'
      .viewport-split
        .price-from
          = select_tag :price_from, 
            options_for_select(@price_from_steps, params[:price_from]), 
            prompt: 'Цена "от"'
        .price-to
          = select_tag :price_to, 
            options_for_select(@price_to_steps, params[:price_to]), 
            prompt: 'Цена "до"'
      = hidden_field_tag :sort
      = hidden_field_tag :dir
      = submit_tag

app/views/flats/_flat.html.slim
.flat(id="flat-#{flat.id}" class= cycle('odd', 'even') data-remote="true" data-url= flat_url(flat))
  .date= flat.actual_at_date
  .address= flat.address
  .district= flat.district.shown_name
  .type= flat.type.shown_name
  .price
    = flat.price 
    | &nbsp;руб
  .phone
    / = #link_to "Узнать телефон", "#", class: 'show-phone button', data: {modal: "login"}
    = flat.contact

app/views/flats/_grid.html.slim
#flats
  .header
    .date.desc(data-sort="actual_at") Дата
    .address(data-sort="address") Адрес
    .district(data-sort="district_id") Район
    .type(data-sort="type_id") Комнат
    .price(data-sort="price") Цена
    .phone Телефон
  #flats-grid
    .page(id="page-#{@flats.current_page}")
      = render @flats
  #pagination
    = render 'flats/pagination'

app/views/flats/_pagination.html.slim
= paginate @flats, params: { controller: :flats, action: :index }

app/views/flats/index.html.slim
= render 'finder'
= render 'grid'

app/views/flats/index.js.erb
<%- if params[:page].present? %>
  $("#flats-grid").append("<div class='page' id='page-<%= @flats.current_page %>'><%= j(render @flats) %></div>"); 
<%- else %>
  $("#flats-grid").html("<div class='page' id='page-<%= @flats.current_page %>'><%= j(render @flats) %></div>"); 
  $('#finder').scrollHere()
<%- end %>

$('#page-<%= @flats.current_page %> .flat').flatDetails()
$('#page-<%= @flats.current_page %> .show-phone').modalize()
$("#pagination").html("<%= j(render 'pagination') %>");

app/views/flats/show.html.slim
- meta og: { image: full_url(@flat.og_preview.url) }
#flat
  h2= @flat.address
  .flat-info
    .map= @flat.static_map
    .description
      table
        tr
          th Адрес
          td = @flat.address
        tr
          th Район
          td = @flat.district.name
        tr
          th Комнат
          td = @flat.type.name
        tr
          th Цена
          td = "#{@flat.price} руб."
        tr
          th Телефон
          td = @flat.is_promo? ? @flat.phone : @flat.contact
      p = @flat.description.html_safe
  .similar
    - @flat.similars.each do |similar|
      .similar-flat
        p = link_to similar.address, similar
        p = similar.district.name
        p = similar.type.name
        p = "#{similar.price} руб."

app/views/flats/show.js.erb
$('#flat-<%= @flat.id %>').after("<%= escape_javascript(render partial: 'details', locals: {flat: @flat}) %>");

$('#flat-<%= @flat.id %>-details').hide();

var img = new Image();
img.onload = function() {
  $('.ajax-loader').remove();
  $('#flat-<%= @flat.id %>-details').show();
  $('#flat-<%= @flat.id %>').scrollHere();
}

img.src = $('#flat-<%= @flat.id %>-map').attr('src');

app/views/home/show.html.slim
/ = render 'shared/hiw'
= render 'shared/benefits'
= render 'flats/finder'
= render 'flats/grid'

app/views/layouts/application.html.slim
doctype html
html
  head
    = metamagic site: "Аренда квартир в Новосибирске", title: [:title, :site], separator: " — "
    meta(name="viewport" content="width=device-width,initial-scale=1")
    = stylesheet_link_tag 'application', media: 'all'
    = google_webfonts_link_tag open_sans: [400], subset: 'cyrillic'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    #wrap
      / Navigation
      header.navigation.magick-wrapper
        .mask
          .menu-wrapper
            h1
              a.logo(href="#{root_path}") Аренда квартир в Новосибирске
            nav
              = render_navigation
            a#menu-toggler(href="#") Меню
          = render 'shared/header'
      / Main
      .magick-wrapper
        .main(role="main")
          = yield
      - unless user_signed_in?
        = render "shared/login"
      = render "shared/footer"
      = render "shared/ga"

app/views/orders/create.html.slim
h3 Перенаправление на страницу оплаты, подождите...

p Если перенаправление не произошло, самостоятельно нажмите на кнопку "оплатить"

= liqpay_button @liqpay_request, title: "Оплатить"

coffee:
  $ ->
    $('#liqpay_form').submit()

app/views/orders/index.html.slim
h3 Ваш платеж поступил в обработку. Пожалуйста, ожидайте результата. Как только придет подтверждение оплаты, ваш срок подписки на премиум сервисы обновится.

app/views/pages/about.html.slim
p Рады представить вам нашу службу эффективного поиска комнат и квартир Sherlock Homes. Мы занимаемся тем, что помогаем вам быстро и без особых затрат найти то самое заветное жилище, которое вы наполните уютом и теплом. 
p Почему заветное? Потому что вопросы места жительства всегда самые острые и актуальные: с одной стороны поджимают финансы, с другой стороны караулит время, а точнее его ограниченные рамки. Вот и получается, что нужно как можно быстрее и как можно удачней. Именно этим мы и занимаемся, мы помогаем найти самые подходящие, именно вам, варианты жилья. Не волнуйтесь, мы не типичное агентство недвижимости, скорее наоборот, мы крайне негативно настроены против агентов и риэлторов, которые обдирают нуждающихся людей своими космическими комиссиями. 
p Мы помогаем вам совершенно другим образом: открываем для вас просторы недвижимости целого города. То есть, вы получаете в пользование целую базу недвижимости с самыми свежими и актуальными вариантами комнат и квартир, сдающихся в аренду. Если вы не верите, что это действительно правда, то можете воспользоваться пробной версией базы и получить один номер, заинтересовавшего именно вас варианта, совершенно бесплатно. 
p Мы не навязываем и не подсовываем вам никаких контактов, вы сами решаете, какой вариант вы хотите открыть для связи с владельцем. Далее вам надо будет просто позвонить арендатору и договориться о встрече в квартире, а там уже сами решайте, но знайте, что вас ждет еще целая база, подходящих альтернатив, так что, выбирайте лучшее…

app/views/pages/contacts.html.slim
h2 Контакты

p Чтобы получить доступ к нашей базе данных квартир собственников и узнать детали по оплате, свяжитесь с нами, используя следующие контактные данные:

p 
  strong Вконтакте: 
  = link_to 'http://vk.com/nervercorameiro', 'http://vk.com/nervercorameiro'
p 
  strong Email: 
  | nervercorameiro@gmail.com

p Извините за причененные неудобства. В самом ближайшем времени сайт будет принимать оплату в автоматическом режиме.

app/views/pages/prices.html.slim
#prices-table
  h2 Тарифные планы
  .prices
    .price-box
      = form_tag orders_path do
        = hidden_field_tag :amount, 99
        .header 1 день 
        .price 99 руб
        .body 
          p Подойдет если вы уверены в своих силах и не хотите тратить много времени на поиски квартиры или комнаты.
        - if user_signed_in? 
          = submit_tag "Купить", class: 'buy'
        - else
          = link_to "Купить", '#', class: 'buy register'
    .price-box.popular
      = form_tag orders_path do
        = hidden_field_tag :amount, 390
        .header 5 дней
        .price 390 руб
        .body 
          p Оптимальный выбор! За небольшую стоимость вы получите достаточно времени для поиска жилья!
        - if user_signed_in? 
          = submit_tag "Купить", class: 'buy'
        - else
          = link_to "Купить", '#', class: 'buy register'
    .price-box
      = form_tag orders_path do
        = hidden_field_tag :amount, 990
        .header 15 дней
        .price 990 руб
        .body 
          p Отлично подойдет тем, кто с особой тщательностью подходит к выбору. У вас будет достаточно времени для поиска лучшего варианта!
        - if user_signed_in? 
          = submit_tag "Купить", class: 'buy'
        - else
          = link_to "Купить", '#', class: 'buy register'
    .price-box
      = form_tag orders_path do
        = hidden_field_tag :amount, 1490
        .header 30 дней
        .price 1490 руб
        .body 
          p Тариф для тех кто ищет что-то спецефическое или наиболее привлекательное по качеству и цене! 
        - if user_signed_in? 
          = submit_tag "Купить", class: 'buy'
        - else
          = link_to "Купить", '#', class: 'buy register'
    .clearfix

  p Мы подошли с особой тщательностью к составлению наших тарифных планов для того, чтобы каждый смог найти для себя именно тот, который ему нужен. Вы можете выбрать как более дешевые тарифные планы, для быстрого поиска квартир и комнат, так и тарифы, предоставляющие больше времени для более тщательного поиска варианта.

  p После покупки определенного тарифа, вы сможете пользоваться нашей базой данных квартир и комнат сдаваемых непосредственно собственниками. Никаких ограничений не накладывается, вы сможете подбирать сколько угодно вариантов в любом районе города.

app/views/shared/_benefits.html.slim
section#benefits
  h2 Почему именно мы?
  .benefit
    .money
    .header У нас выгодно!
    / .details
      / p Очевидная экономия финансов и времени – два самых ценных ресурса, когда вам так необходима уютная крыша над головой. Вам не нужно платить бешенную комиссию за работу агентства и не нужно тратить время, пока подвернется более-менее удачный вариант, если вы ищете квартиру через друзей, знакомых и репосты.
  .benefit
    .fire
    .header У нас горячие предложения! 
    / .details
      / p Наша база постоянно обновляется и редактируется модераторами. Вы всегда получаете самую актуальную и достоверную информацию на сегодняшний день. Не получится так, что вы позвоните владельцу, а квартира уже месяц как сдана или вообще, больше не сдается. Только самые горячие и актуальные варианты.
  .benefit
    .thumb
    .header С нами удобно!
    / .details
      / p На сайте работает крайне простой и удобный процесс поиска подходящих именно вам вариантов жилья. Также вы можете выбрать тот способ оплаты, который полностью вам подойдет. Если у вас возникнут какие-либо трудности, то наша служба поддержки всегда готова придти к вам на помощь!
  .benefit
    .heart
    .header С нами приятно иметь дело!
    / .details
      / p На нашем сайте вы можете найти множество приятных бонусов и полезных моментов. Для вас мы подготовили целый раздел юридической помощи по вопросам аренды недвижимости; вы можете активировать пробную версию нашей базы и открыть один контакт, понравившейся вам квартиры абсолютно бесплатно!

app/views/shared/_footer.html.slim
footer#footer.magick-wrapper
  .inner
    .col
      | Наша группа &nbsp;
      = link_to 'ВКонтакте', "http://vk.com/sherlockhomez"
    .col
      ul
        li = link_to "Как оплатить", "#"
        li = link_to "Цены", page_path(:prices)
        li = link_to "О нас", page_path(:about)
        li = link_to "Контакты", page_path(:contacts)
    .col Sherlock Homes - ваш помощник в поиске сдаваемых в аренду доступных комнат и квартир. Никаких посредников и переплат! Только качественные и актуальные объявления!
    .col Просим принять во внимание, что все мы люди и все мы делаем ошибки. Наши менеджеры не являются исключением. Некоторые объявления в нашей базе могут оказаться устаревшими или не актуальными. В крайнем случае просим вас обратиться к службе поддержки.

app/views/shared/_header.html.slim
#intro
  h2 Аренда квартир в Новосибирске
  p Поиск жилой площади в аренду еще никогда не был таким простым для вас. Никаких посредников и нереальных переплат! Только собственники и реальные предложения!
  = link_to 'Найти квартиру', root_path + '#finder', class: 'button big-button', id: "start-search"

app/views/shared/_hiw.html.slim
section#hiw
  h2 Как это работает?
  p Штат наших менеджеров собирает и обрабатывает множество объявлений по всему интернету, оставляя только лишь актуальные объявления от собственников квартир. Таким образом создается постоянно обновляемая база данных отборных объявлений от собственников квартир. 
  p Наш сервис - это предоставление вам полного доступа к нашей тщательно подобранной базе данных. Вы с легкостью сможете найти необходимую вам квартиру или комнату, используя фильтры: по цене, району, количеству комнат, улице.
  p Используя нашу базу данных собственников по квартирам и комнатам города Новосибирска, вы без труда сможете в кратчайшие сроки подобрать себе самое качественное и доступное жилье, без лишних проблем и временных затрат.

app/views/shared/_login.html.slim
#login.modal-wrapper
  a.modal-close(href="#") &times;
  .login-wrapper
    .login-inner
      .login-button-wrapper
        a.login-button.vk-btn(href="/auth/vkontakte")
          span.login-label Войти через ВКонтакте 
      .login-button-wrapper
        a.login-button.fb-btn(href="/auth/facebook")
          span.login-label Войти через Facebook
      .login-button-wrapper
        a.login-button.tw-btn(href="/auth/twitter")
          span.login-label Войти через Twitter
      p
        small Чтобы воспользоваться нашими услугами, пожалуйста, осуществите вход на сайт, используя одну из ваших любимых соцсетей